### ISSUE TITLE
projj remove

### ISSUE THREAD

**Issue by popomore** [popomore/projj#17]
1. rm -rf 
1. clean cache.json

**Comment by DiamondYuan** [comment]
有一个疑惑。如果一个目录下的仓库全部被删除了，而且这个目录是空的，那么要不要删除这个目录呢？

**Comment by DiamondYuan** [comment]
如果不删除的话可能会残留一堆空文件夹。


也可以提供一个类似 projj clean 的命令来清除

**Comment by popomore** [comment]
应该要删除，还要从缓存中删除记录
